import TodoList from "./TodoList";

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'TodoList',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex">
      <div>
        <TodoList />
      </div>
      <div className="flex-1">{children}</div>
    </main>
  );
}
